### PR TITLE
fix(webapp): add hook for handle image load

### LINKED ISSUE #81: Add loader in avatar component
Image

### PR DESCRIPTION
**Pull request by tetogomez**
### What does this PR do?

- Resolve #81 

### Steps to test

1. first step
2. next step

#### CheckList

- [] Follow proper Markdown format
- [] The content is adequate
- [] The content is available in both english and spanish
- [] I Ran a spell check

### CODE REVIEW

File: src/components/ImageLoad/index.tsx [hunk 1]
```diff
@@ -0,0 +1,25 @@
+/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
+/* eslint-disable @next/next/no-img-element */
+import React from 'react'
+
+import useImageOnLoad from 'hooks/useImageLoading'
+
+const ImgLoading = ({ img, classes, defaultImg }) => {
+  const { imgUrl, css } = useImageOnLoad(img)
+
+  console.log({ imgUrl })
```
Comment (xavier506) [inline src/components/ImageLoad/index.tsx:10]: console.log?

File: src/hooks/useImageLoading/index.tsx [hunk 2]
```diff
@@ -0,0 +1,60 @@
+/* eslint-disable @typescript-eslint/explicit-module-boundary-types */
+import { useState, useEffect } from 'react'
+
+import { useSharedState } from 'context/state.context'
+
+const _cachedImage = async (img: string, setImgCallback: any) => {
+  const res = await fetch(`https://ipfs.io/ipfs/${img}`)
```
Comment (xavier506) [inline src/hooks/useImageLoading/index.tsx:7]: Eden has its own IPFS gateway which may be better to use:

https://eden-genesis.mypinata.cloud/ipfs/

**Review by AngeloCG97 — APPROVED** [review]
LGTM
