### PR TITLE
fix: fix issues related to delegator page

### LINKED ISSUE #271: Improve the format of the countdown

### LINKED ISSUE #272: Improve the recipient account input

### LINKED ISSUE #273: There is no spanish version for the Undelegate button

### LINKED ISSUE #274: Fix eslint issue for popper (sidebar component)

### LINKED ISSUE #275: remove spinner from auth button

### LINKED ISSUE #276: Add logic to undelegate vote

### PR DESCRIPTION
**Pull request by tetogomez**
### What does this PR do?

- Resolve #271 
- Resolve #272 
- Resolve #273 
- Resolve #274 
- Resolve #275 
- Resolve #276 

### Steps to test

1. run `yarn dev`
2. go to `localhost:3000`

#### CheckList

- [] Follow proper Markdown format
- [] The content is adequate
- [] The content is available in both english and spanish
- [] I Ran a spell check

### CODE REVIEW

File: src/hooks/useUAL/index.tsx [hunk 1]
```diff
@@ -22,21 +22,27 @@ const useLightUAL = ({ appName, chains, authenticators }: UALType) => {
...
+      })
 
-    setLoading(true)
-    authenticateWithoutAccountInput({
-      ual,
-      appName,
-      availableAuthenticators,
-      authenticator
-    })
+      console.log({ response })
```
Comment (AngeloCG97) [inline src/hooks/useUAL/index.tsx:42]: Is need this comment?

**Review by AngeloCG97 — APPROVED** [review]
LGTM

**Review by xavier506 — APPROVED** [review]
LGTM
